[package]
name = "beef_market"
version = "0.1.0"
edition = "2021"

[dependencies]
fantoccini = "0.21.2"
headless_chrome = "1.0.15"
reqwest = { version = "0.12.9", features = ["json", "native-tls"] }
scraper = "0.21.0"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
